on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - run: pip install -r requirements.txt pyinstaller==4.9
    - name: Create binary
      run: pyinstaller -F -s -n clientcerts-${RUNNER_OS}-${RUNNER_ARCH} clientcerts/__main__.py
      shell: bash
    - name: Pack binary
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        files: |
          ./dist/*
        args: -fq
      if: $RUNNER_OS != 'macOS'
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
